	PRINT 'Creating tables'
	CREATE TABLE PRODUCT(
		[PRODUCT_ID] INT NOT NULL IDENTITY,
		[NAME] VARCHAR(MAX) NULL,
		[LOGIN] VARCHAR(MAX) NULL,
		[PASSWORD] VARCHAR(MAX) NULL
	);
GO

	PRINT 'Scripts finished'
GO